[package]
name = "bustcall"
version = "0.1.0"
edition = "2021"

[lib]
name = "bustcall_core"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "bustcall"
required-features = ["cli"]

[dependencies]
# Core dependencies (always available)
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
notify = "6.1"
sha2 = "0.10"
hex = "0.4"

# Optional CLI dependencies
clap = { version = "4.5", features = ["derive"], optional = true }

# FFI bindings (optional)
pyo3 = { version = "0.20", optional = true }

[features]
default = []
cli = ["clap"]
python-bindings = ["pyo3"]
all = ["cli", "python-bindings"]

[profile.release]
opt-level = "z"
lto = true
