[package]
name = "bustcall"
version = "0.1.0"
edition = "2021"
description = "OBINexus CI/CD bustcall daemon and core library"
license = "MIT"
repository = "https://github.com/obinexus/bustcall"

[lib]
name = "bustcall_core"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

# Primary CLI binary
[[bin]]
name = "bustcall"
path = "src/cli/main.rs"
required-features = ["cli"]

# Daemon binary
[[bin]]
name = "bustcall-daemon"
path = "src/daemon/main.rs"
required-features = ["daemon"]

[features]
default = ["cli"]
cli = ["clap", "tokio"]
daemon = ["tokio", "serde", "serde_json"]
python-bindings = ["pyo3"]
ffi = ["libc"]

[dependencies]
# Core dependencies
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
thiserror = "1.0"

# CLI features
clap = { version = "4.0", features = ["derive"], optional = true }

# Async runtime
tokio = { version = "1.0", features = ["full"], optional = true }

# Serialization
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

# FFI bindings
pyo3 = { version = "0.20", features = ["extension-module"], optional = true }
libc = { version = "0.2", optional = true }

[dev-dependencies]
tempfile = "3.0"
assert_cmd = "2.0"
predicates = "3.0"

[build-dependencies]
pyo3-build-config = { version = "0.20", optional = true }

# Python extension configuration
[tool.cibuildwheel]
build = "cp38-* cp39-* cp310-* cp311-*"
skip = "*-win32 *-manylinux_i686"

[package.metadata.maturin]
name = "bustcall_core"
module-name = "bustcall_core"